###

# curl 'http://127.0.0.1/login'
#  -H 'Accept: */*'
#  -H 'Accept-Language: zh,en;q=0.9,zh-TW;q=0.8,zh-CN;q=0.7,en-US;q=0.6'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'
#  -H 'DNT: 1'
#  -H 'Origin: http://127.0.0.1'
#  -H 'Pragma: no-cache'
#  -H 'Referer: http://127.0.0.1/logout'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'
#  -H 'X-Requested-With: XMLHttpRequest'
#  -H 'sec-ch-ua: "Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw 'username=admin&password=12345678&validateCode=5&rememberMe=false'
POST http://127.0.0.1/login
Accept: */*
Accept-Language: zh,en;q=0.9,zh-TW;q=0.8,zh-CN;q=0.7,en-US;q=0.6
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Origin: http://127.0.0.1
Pragma: no-cache
Referer: http://127.0.0.1/logout
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
sec-ch-ua: "Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username = admin &
password = 12345678 &
validateCode = 5 &
rememberMe = false

###

